<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="methods" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="com.qa.testcases.testNg.listner.MyAnnotationTransformer"/>
    <listener class-name="com.qa.testcases.testNg.listner.MyTestListner"/>
  </listeners>
  <test thread-count="5" parallel="methods" name="TestTwo(failed)">
    <parameter name="password" value="testing@123"/>
    <parameter name="baseurl" value="https://www.yahoo.com/"/>
    <parameter name="email" value="test@yahoo.com"/>
    <classes>
      <class name="com.qa.testcases.testNg.RetryLogic">
        <methods>
          <include name="noRetryOnFailure"/>
        </methods>
      </class> <!-- com.qa.testcases.testNg.RetryLogic -->
    </classes>
  </test> <!-- TestTwo(failed) -->
</suite> <!-- Failed suite [Suite] -->
